// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/corentings/kafejo-bot/app/commands/versioncommand"
	"github.com/corentings/kafejo-bot/app/handler"
)

// Injectors from wire.go:

func InitializeVersion() versioncommand.Command {
	iHandler := handler.GetHandler()
	command := versioncommand.NewCommand(iHandler)
	return command
}
